### ISSUE TITLE
module break order view in backend - M2 2.1.7

### ISSUE THREAD

**Issue by moneef** [fraudlabspro/magento2#6]
Hey guys,

i installed the module using `composer require hexasoft/module-fraudlabspro`, magneto version 2.1.7
when i try to view order details from Sales -> Orders -> select view order the page breaks

i did install boldcommerce/magento2-ordercomments but it doesn't do anything with javascript on the admin sales/order/view page, when : 

> fraudlabspro Disabled | OrderComment Enabled = working fine
> fraudlabspro Enabled | OrderComment Disabled = working fine
> fraudlabspro Disabled | OrderComment Disabled = working fine
> fraudlabspro Enabled | OrderComment Enabled = Error
> 

the page error : 
```
Order View
Information Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
Invoices Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
Credit Memos Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
Shipments Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
Comments History Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
FraudLabs Pro Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.
```

console log :

```
(index):322 Uncaught ReferenceError: require is not defined
    at (index):322
(anonymous) @ (index):322
(index):421 Uncaught ReferenceError: require is not defined
    at (index):421
(anonymous) @ (index):421
(index):437 Uncaught ReferenceError: require is not defined
    at (index):437
(anonymous) @ (index):437
```
html page error :

```
<b>Fatal error</b>:  Uncaught Error: Call to a member function registry() on null in /home/moneef/public_html/vendor/magento/module-sales/Block/Adminhtml/Order/AbstractOrder.php:59
--
  | Stack trace:
  | #0 /home/moneef/public_html/vendor/boldcommerce/magento2-ordercomments/Plugin/Block/Adminhtml/SalesOrderViewInfo.php(20): Magento\Sales\Block\Adminhtml\Order\AbstractOrder-&gt;getOrder()
  | #1 /home/moneef/public_html/vendor/magento/framework/Interception/Interceptor.php(152): Bold\OrderComment\Plugin\Block\Adminhtml\SalesOrderViewInfo-&gt;afterToHtml(Object(Hexasoft\FraudLabsPro\Block\Adminhtml\Order\View\Info\Interceptor), '\n\t\t&lt;div class=&quot;...')
  | #2 /home/moneef/public_html/var/generation/Hexasoft/FraudLabsPro/Block/Adminhtml/Order/View/Info/Interceptor.php(26): Hexasoft\FraudLabsPro\Block\Adminhtml\Order\View\Info\Interceptor-&gt;___callPlugins('toHtml', Array, Array)
  | #3 /home/moneef/public_html/vendor/hexasoft/module-fraudlabspro/view/adminhtml/templates/order/view/tab/flpsummary.phtml(2): Hexasoft\FraudLabsPro\Block\Adminhtml\Order\Vie in <b>/home/moneef/public_html/vendor/magento/module-sales/Block/Adminhtml/Order/AbstractOrder.php</b> on line <b>59</b><br />
```

**Comment by fraudlabspro-com** [comment]
Hi @moneef, we are unable to produce the issue you reported. It is working fine from our testing.

**Comment by moneef** [comment]
Hello @fraudlabspro,

sorry i should have closed this, the issue has been solved by @boldsidney on https://github.com/boldcommerce/magento2-ordercomments/issues/9.

thank you guys for trying.
